# Generated by Django 4.0.6 on 2022-11-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
